config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboards#index'
  resources :dashboards do
    collection do
      patch :sort
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  belongs_to :user

  validates :headline, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable
  has_many :dashboards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  before_action :authenticate_user!

  def index
    @dashboards = current_user.dashboards.order(:position)
  end

  def new
    @dashboard = current_user.dashboards.build
  end

  def create
    current_user.dashboards.create(dashboard_params)
    flash[:notice] = 'Dashboard created!'
    redirect_to root_path
  end

  def edit
    @dashboard = Dashboard.find(params[:id])
  end

  def update
    current_user.dashboards.find(params[:id]).update(dashboard_params)
    flash[:notice] = 'Dashboard updated!'
    redirect_to root_path
  end

  def sort
    params[:dashboard].each_with_index do |id, index|
      current_user.dashboards.find_by(id: id).update_attribute(:position, index + 1)
    end
    head :ok
  end

  private

  def dashboard_params
    params.require(:dashboard).permit(:headline, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/_form.html.erb
<%= link_to "Back", root_path, class: 'btn bg-light' %>
<br>
<br>
<h4>Dashboard</h4>
<br>
<%= form_for @dashboard do |f| %>
  <% if f.object.errors.any? %>
    <ul class="alert alert-danger">
      <% f.object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= f.label "Headline*" %>
    <%= f.text_field :headline, class: "form-control", required: true %>
    <br>
    <%= f.label "Content" %>
    <%= f.text_field :content, class: "form-control" %>

    <br>
    <%= f.submit "Submit", class: "btn bg-secondary" %>
  </div>
<% end %>

app/views/dashboards/edit.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-4">
      <strong>It is possible to edit Your existing Dashboard here.</strong>
    </div>
  </div>
</div>

app/views/dashboards/index.html.erb
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-7">
      <% if @dashboards.present? %>
        <h2>Your Dashboards</h2>
        <br>
        <div id="dashboards" class="list-group" data-url="<%= sort_dashboards_path %>">
          <% @dashboards.each do |dashboard| %>
            <div class="card mt-4", id= "<%=dom_id(dashboard) %>">
              <h5 class="card-header"><%=dashboard.headline%></h5>
              <div class="card-body">
                <p class="card-text"><%=dashboard.content%></p>
                <span class="float-right"><%= link_to "Edit", edit_dashboard_path(dashboard), class: 'btn bg-secondary' %></span>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <h5>You don't have any Dashboards yet. Click 'New'
         in navigation menu to create one.</h5>
      <% end %>
    </div>
    <div class="col-md-1"></div>
    <div class="col-md-4">
      <br>
      <br>
      <strong>You will be able to use <i>drag&drop</i> to reorder dashboards. Position will be saved to db.</strong>
    </div>
  </div>
</div>

app/views/dashboards/new.html.erb
<br>
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <%= render 'form' %>
    </div>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-4">
      <br>
      <strong>Create a new Dashboard Widget</strong>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <%= link_to "Dashboard", root_path, class: 'navbar-brand' %>
  
  <div class="collapse navbar-collapse" id="nav-content">
  <ul class="navbar-nav">
    <% if current_user.present? %>
      <li class="nav-item <%= 'active' if action_name == 'new' %>">
        <%= link_to 'New', new_dashboard_path, class: 'nav-link' %>
      </li>
    <% end %>
  </ul>

  <% if current_user.present? %>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <div class="navbar-text">
          <%= current_user.email %>
        </div>
      </li>

      <li class="nav-item">
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
    </ul>
  <% end %>
</nav>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DashboardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag '//ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/le-frog/jquery-ui.min.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="header">
      <%= render partial: 'layouts/header' %>
    </div>
    <div id="content">
      <div class="container">
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
          <br>
        <% end %>
        
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>